[platformio]
default_envs = standard, color_coded_clock
src_dir = .
include_dir = .

[env]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.6.0
build_flags =
    -DFASTLED_INTERRUPT_RETRY_COUNT=0

[env:standard]
build_flags =
    ${env.build_flags}

[env:color_coded_clock]
build_flags =
    ${env.build_flags}
    -DCOLOR_CODED_CLOCK
